### ISSUE TITLE
Cannot add imports for builtins

### ISSUE THREAD

**Issue by wiedzmin** [yasushi-saito/go-imports#1]
When, for example, I need to use "signal" package from "os/signal", I cannot find it in list of provided variants (obviously, after packages list reloading). I know about Golang temptation of doing internal things behind the scene (with no respective interfaces available outwards, forcing users to invent bicycles therefore), but anyway above problem is quite frustrating...

**Comment by yasushi-saito** [comment]
If GOROOT is set, stuff under $GOROOT/src should be indexed. It's possible to auto-detect the location of GOROOT if it's not set, but the current code doesn't do that.

**Comment by yasushi-saito** [comment]
https://github.com/yasushi-saito/go-imports/commit/f025bbd72690f1145f13659bd1389125ce7b424b should have fixed the issue.

**Comment by wiedzmin** [comment]
@yasushi-saito Thanks a lot!
